cmake_minimum_required (VERSION 3.12)

project(SchweinProject)

set(CMAKE_CXX_STANDARD 17)
set_property(GLOBAL PROPERTY USE_FOLDERS ON)

set(OUTPUT_DIR ${CMAKE_SOURCE_DIR}/build/${PLATFORM_ARCHITECTURE}/$<CONFIG>)
set(PROJ_CONFIG $<CONFIG>)

enable_testing()

add_executable(
	SchweinProject 
	source/main.cpp
        source/tiere/Schwein.h
		source/collections/Stapel.h
		source/services/Dependency.h
		source/services/DependencyImpl.h
		source/services/MyServiceUsingDependency.h
		source/services/DemoDep.h
		source/services/Multiplizierer.h
		source/services/MultipliziererImpl.h
		source/services/MultipliziererOptimierer.h
)


# Add tests
add_subdirectory(tests)

